# Site settings
title: TWVAL
email: info@twval.org
description: > # this means to ignore newlines until "baseurl:"
  Taiwan Vapor Advocacy League
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost" # the base hostname & protocol for your site
twitter: TaiwanVapeAL
facebook: twval

exclude: [ vendor, Gemfile, Gemfile.lock, README.md, deploy.sh ]


# Build settings
markdown: kramdown

linkblog:
  linkpost:
    marker: →
    marker_position: after
  posts:
    marker: false
    marker_position: before

  titlecase: false
  unorphan: false
  permalink_label: Permalink

language_names:
  en: English
  tw: 正體中文
lang: en
